syntax = "proto3";

package pb;
option go_package=".;pb";

service FileTransfer {
  rpc StreamReceive(stream File) returns (File) {}
  rpc Head(File) returns (File) {}
  rpc SyncMisc(Misc) returns (Misc) {}
}

message File {
  int32   action = 1;
  string  comment = 2;
  string fpath = 3;
  string fhash = 4;
  int64  fsize = 5;
  string chunkHash = 6;
  int32 chunkNum = 7;
  int32 chunkTotal = 8;
  int64 chunkOffset = 9;
  int64 chunkSize = 10;
  bytes finfo = 11;
  bytes chunkData = 12;
}

message Misc {
  string type = 1;
  bytes data = 2;
}


