[req]  
req_extensions = v3_req  
distinguished_name = req_distinguished_name  
prompt = no  
  
[req_distinguished_name]  
countryName = US  
stateOrProvinceName = state  
localityName = city  
organizationName = zcp  
commonName = zcp  
  
[v3_req]  
subjectAltName = @alt_names  
  
[alt_names]  
DNS.1 = files.zcp.corpnet
