// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: entity.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type File struct {
	Status               int32    `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Comment              []byte   `protobuf:"bytes,2,opt,name=comment,proto3" json:"comment,omitempty"`
	Path                 []byte   `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Ftype                []byte   `protobuf:"bytes,4,opt,name=ftype,proto3" json:"ftype,omitempty"`
	Finfo                []byte   `protobuf:"bytes,5,opt,name=finfo,proto3" json:"finfo,omitempty"`
	Fsum                 []byte   `protobuf:"bytes,6,opt,name=fsum,proto3" json:"fsum,omitempty"`
	Fsize                int64    `protobuf:"varint,7,opt,name=fsize,proto3" json:"fsize,omitempty"`
	OffsetFrom           int64    `protobuf:"varint,8,opt,name=offsetFrom,proto3" json:"offsetFrom,omitempty"`
	OffsetTo             int64    `protobuf:"varint,9,opt,name=offsetTo,proto3" json:"offsetTo,omitempty"`
	Data                 []byte   `protobuf:"bytes,10,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *File) Reset()         { *m = File{} }
func (m *File) String() string { return proto.CompactTextString(m) }
func (*File) ProtoMessage()    {}
func (*File) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{0}
}
func (m *File) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *File) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_File.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *File) XXX_Merge(src proto.Message) {
	xxx_messageInfo_File.Merge(m, src)
}
func (m *File) XXX_Size() int {
	return m.Size()
}
func (m *File) XXX_DiscardUnknown() {
	xxx_messageInfo_File.DiscardUnknown(m)
}

var xxx_messageInfo_File proto.InternalMessageInfo

func (m *File) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *File) GetComment() []byte {
	if m != nil {
		return m.Comment
	}
	return nil
}

func (m *File) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *File) GetFtype() []byte {
	if m != nil {
		return m.Ftype
	}
	return nil
}

func (m *File) GetFinfo() []byte {
	if m != nil {
		return m.Finfo
	}
	return nil
}

func (m *File) GetFsum() []byte {
	if m != nil {
		return m.Fsum
	}
	return nil
}

func (m *File) GetFsize() int64 {
	if m != nil {
		return m.Fsize
	}
	return 0
}

func (m *File) GetOffsetFrom() int64 {
	if m != nil {
		return m.OffsetFrom
	}
	return 0
}

func (m *File) GetOffsetTo() int64 {
	if m != nil {
		return m.OffsetTo
	}
	return 0
}

func (m *File) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Misc struct {
	Mtype                string   `protobuf:"bytes,1,opt,name=mtype,proto3" json:"mtype,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Misc) Reset()         { *m = Misc{} }
func (m *Misc) String() string { return proto.CompactTextString(m) }
func (*Misc) ProtoMessage()    {}
func (*Misc) Descriptor() ([]byte, []int) {
	return fileDescriptor_cf50d946d740d100, []int{1}
}
func (m *Misc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Misc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Misc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Misc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misc.Merge(m, src)
}
func (m *Misc) XXX_Size() int {
	return m.Size()
}
func (m *Misc) XXX_DiscardUnknown() {
	xxx_messageInfo_Misc.DiscardUnknown(m)
}

var xxx_messageInfo_Misc proto.InternalMessageInfo

func (m *Misc) GetMtype() string {
	if m != nil {
		return m.Mtype
	}
	return ""
}

func (m *Misc) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*File)(nil), "pb.File")
	proto.RegisterType((*Misc)(nil), "pb.Misc")
}

func init() { proto.RegisterFile("entity.proto", fileDescriptor_cf50d946d740d100) }

var fileDescriptor_cf50d946d740d100 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x3f, 0x4e, 0xf3, 0x40,
	0x10, 0xc5, 0xb3, 0x89, 0xf3, 0x6f, 0x94, 0xaf, 0x19, 0x7d, 0x8a, 0x56, 0x11, 0x32, 0x51, 0x1a,
	0x5c, 0x59, 0x08, 0x4a, 0x3a, 0x8a, 0x40, 0x83, 0x84, 0x4c, 0x2a, 0xba, 0x75, 0x32, 0x16, 0x96,
	0xb0, 0xd7, 0xf2, 0x4e, 0x90, 0xc2, 0x45, 0xe0, 0x48, 0x94, 0x1c, 0x01, 0x99, 0x1b, 0x70, 0x02,
	0xb4, 0xbb, 0xc1, 0x50, 0x20, 0xba, 0xf7, 0x7b, 0xf3, 0x9e, 0x66, 0xec, 0x85, 0x09, 0x95, 0x9c,
	0xf3, 0x2e, 0xae, 0x6a, 0xcd, 0x1a, 0xbb, 0x55, 0xba, 0xf8, 0x10, 0x10, 0x2c, 0xf3, 0x7b, 0xc2,
	0x29, 0x0c, 0x0c, 0x2b, 0xde, 0x1a, 0x29, 0xe6, 0x22, 0xea, 0x27, 0x7b, 0x42, 0x09, 0xc3, 0xb5,
	0x2e, 0x0a, 0x2a, 0x59, 0x76, 0xe7, 0x22, 0x9a, 0x24, 0x5f, 0x88, 0x08, 0x41, 0xa5, 0xf8, 0x4e,
	0xf6, 0x9c, 0xed, 0x34, 0xfe, 0x87, 0x7e, 0xc6, 0xbb, 0x8a, 0x64, 0xe0, 0x4c, 0x0f, 0xce, 0xcd,
	0xcb, 0x4c, 0xcb, 0xfe, 0xde, 0xb5, 0x60, 0xfb, 0x99, 0xd9, 0x16, 0x72, 0xe0, 0xfb, 0x56, 0xbb,
	0xa4, 0xc9, 0x1f, 0x49, 0x0e, 0xe7, 0x22, 0xea, 0x25, 0x1e, 0x30, 0x04, 0xd0, 0x59, 0x66, 0x88,
	0x97, 0xb5, 0x2e, 0xe4, 0xc8, 0x8d, 0x7e, 0x38, 0x38, 0x83, 0x91, 0xa7, 0x95, 0x96, 0x63, 0x37,
	0x6d, 0xd9, 0x6e, 0xd9, 0x28, 0x56, 0x12, 0xfc, 0x16, 0xab, 0x17, 0xc7, 0x10, 0x5c, 0xe5, 0x66,
	0x6d, 0xb7, 0x15, 0xee, 0x5a, 0xfb, 0xc9, 0xe3, 0xc4, 0x43, 0xdb, 0xe8, 0x7e, 0x37, 0x4e, 0x9e,
	0x04, 0x4c, 0xec, 0x6f, 0x5a, 0xd5, 0xaa, 0x34, 0x19, 0xd5, 0x78, 0x04, 0xff, 0x6e, 0xb8, 0x26,
	0x55, 0x24, 0xb4, 0xa6, 0xfc, 0x81, 0x70, 0x14, 0x57, 0x69, 0x6c, 0x23, 0xb3, 0x56, 0x2d, 0x3a,
	0x91, 0xc0, 0x03, 0x08, 0x2e, 0x49, 0x6d, 0x7e, 0x9f, 0xe3, 0x21, 0x0c, 0x2f, 0x88, 0xdd, 0x31,
	0xce, 0xb6, 0x6a, 0xd6, 0x2a, 0x1f, 0xb8, 0xde, 0xfe, 0x11, 0x38, 0x9f, 0xbe, 0x34, 0xa1, 0x78,
	0x6d, 0x42, 0xf1, 0xd6, 0x84, 0xe2, 0xf9, 0x3d, 0xec, 0xdc, 0x06, 0xf1, 0x59, 0x95, 0xa6, 0x03,
	0xf7, 0xc6, 0xa7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x44, 0x18, 0xca, 0xe9, 0xf3, 0x01, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FileTransferClient is the client API for FileTransfer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FileTransferClient interface {
	StreamReceive(ctx context.Context, opts ...grpc.CallOption) (FileTransfer_StreamReceiveClient, error)
	Head(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error)
	GetMisc(ctx context.Context, in *Misc, opts ...grpc.CallOption) (*Misc, error)
	PutMisc(ctx context.Context, in *Misc, opts ...grpc.CallOption) (*Misc, error)
}

type fileTransferClient struct {
	cc *grpc.ClientConn
}

func NewFileTransferClient(cc *grpc.ClientConn) FileTransferClient {
	return &fileTransferClient{cc}
}

func (c *fileTransferClient) StreamReceive(ctx context.Context, opts ...grpc.CallOption) (FileTransfer_StreamReceiveClient, error) {
	stream, err := c.cc.NewStream(ctx, &_FileTransfer_serviceDesc.Streams[0], "/pb.FileTransfer/StreamReceive", opts...)
	if err != nil {
		return nil, err
	}
	x := &fileTransferStreamReceiveClient{stream}
	return x, nil
}

type FileTransfer_StreamReceiveClient interface {
	Send(*File) error
	CloseAndRecv() (*File, error)
	grpc.ClientStream
}

type fileTransferStreamReceiveClient struct {
	grpc.ClientStream
}

func (x *fileTransferStreamReceiveClient) Send(m *File) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileTransferStreamReceiveClient) CloseAndRecv() (*File, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(File)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileTransferClient) Head(ctx context.Context, in *File, opts ...grpc.CallOption) (*File, error) {
	out := new(File)
	err := c.cc.Invoke(ctx, "/pb.FileTransfer/Head", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferClient) GetMisc(ctx context.Context, in *Misc, opts ...grpc.CallOption) (*Misc, error) {
	out := new(Misc)
	err := c.cc.Invoke(ctx, "/pb.FileTransfer/GetMisc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileTransferClient) PutMisc(ctx context.Context, in *Misc, opts ...grpc.CallOption) (*Misc, error) {
	out := new(Misc)
	err := c.cc.Invoke(ctx, "/pb.FileTransfer/PutMisc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileTransferServer is the server API for FileTransfer service.
type FileTransferServer interface {
	StreamReceive(FileTransfer_StreamReceiveServer) error
	Head(context.Context, *File) (*File, error)
	GetMisc(context.Context, *Misc) (*Misc, error)
	PutMisc(context.Context, *Misc) (*Misc, error)
}

// UnimplementedFileTransferServer can be embedded to have forward compatible implementations.
type UnimplementedFileTransferServer struct {
}

func (*UnimplementedFileTransferServer) StreamReceive(srv FileTransfer_StreamReceiveServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamReceive not implemented")
}
func (*UnimplementedFileTransferServer) Head(ctx context.Context, req *File) (*File, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Head not implemented")
}
func (*UnimplementedFileTransferServer) GetMisc(ctx context.Context, req *Misc) (*Misc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMisc not implemented")
}
func (*UnimplementedFileTransferServer) PutMisc(ctx context.Context, req *Misc) (*Misc, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutMisc not implemented")
}

func RegisterFileTransferServer(s *grpc.Server, srv FileTransferServer) {
	s.RegisterService(&_FileTransfer_serviceDesc, srv)
}

func _FileTransfer_StreamReceive_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileTransferServer).StreamReceive(&fileTransferStreamReceiveServer{stream})
}

type FileTransfer_StreamReceiveServer interface {
	SendAndClose(*File) error
	Recv() (*File, error)
	grpc.ServerStream
}

type fileTransferStreamReceiveServer struct {
	grpc.ServerStream
}

func (x *fileTransferStreamReceiveServer) SendAndClose(m *File) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileTransferStreamReceiveServer) Recv() (*File, error) {
	m := new(File)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileTransfer_Head_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(File)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).Head(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FileTransfer/Head",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).Head(ctx, req.(*File))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransfer_GetMisc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Misc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).GetMisc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FileTransfer/GetMisc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).GetMisc(ctx, req.(*Misc))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileTransfer_PutMisc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Misc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileTransferServer).PutMisc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.FileTransfer/PutMisc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileTransferServer).PutMisc(ctx, req.(*Misc))
	}
	return interceptor(ctx, in, info, handler)
}

var _FileTransfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.FileTransfer",
	HandlerType: (*FileTransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Head",
			Handler:    _FileTransfer_Head_Handler,
		},
		{
			MethodName: "GetMisc",
			Handler:    _FileTransfer_GetMisc_Handler,
		},
		{
			MethodName: "PutMisc",
			Handler:    _FileTransfer_PutMisc_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReceive",
			Handler:       _FileTransfer_StreamReceive_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "entity.proto",
}

func (m *File) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *File) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *File) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x52
	}
	if m.OffsetTo != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.OffsetTo))
		i--
		dAtA[i] = 0x48
	}
	if m.OffsetFrom != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.OffsetFrom))
		i--
		dAtA[i] = 0x40
	}
	if m.Fsize != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.Fsize))
		i--
		dAtA[i] = 0x38
	}
	if len(m.Fsum) > 0 {
		i -= len(m.Fsum)
		copy(dAtA[i:], m.Fsum)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Fsum)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Finfo) > 0 {
		i -= len(m.Finfo)
		copy(dAtA[i:], m.Finfo)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Finfo)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Ftype) > 0 {
		i -= len(m.Ftype)
		copy(dAtA[i:], m.Ftype)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Ftype)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Path) > 0 {
		i -= len(m.Path)
		copy(dAtA[i:], m.Path)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Path)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Comment) > 0 {
		i -= len(m.Comment)
		copy(dAtA[i:], m.Comment)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Comment)))
		i--
		dAtA[i] = 0x12
	}
	if m.Status != 0 {
		i = encodeVarintEntity(dAtA, i, uint64(m.Status))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *Misc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Misc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Misc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Mtype) > 0 {
		i -= len(m.Mtype)
		copy(dAtA[i:], m.Mtype)
		i = encodeVarintEntity(dAtA, i, uint64(len(m.Mtype)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEntity(dAtA []byte, offset int, v uint64) int {
	offset -= sovEntity(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *File) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Status != 0 {
		n += 1 + sovEntity(uint64(m.Status))
	}
	l = len(m.Comment)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	l = len(m.Path)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	l = len(m.Ftype)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	l = len(m.Finfo)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	l = len(m.Fsum)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.Fsize != 0 {
		n += 1 + sovEntity(uint64(m.Fsize))
	}
	if m.OffsetFrom != 0 {
		n += 1 + sovEntity(uint64(m.OffsetFrom))
	}
	if m.OffsetTo != 0 {
		n += 1 + sovEntity(uint64(m.OffsetTo))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *Misc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Mtype)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovEntity(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovEntity(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEntity(x uint64) (n int) {
	return sovEntity(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *File) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: File: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: File: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comment = append(m.Comment[:0], dAtA[iNdEx:postIndex]...)
			if m.Comment == nil {
				m.Comment = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Path", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Path = append(m.Path[:0], dAtA[iNdEx:postIndex]...)
			if m.Path == nil {
				m.Path = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ftype", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ftype = append(m.Ftype[:0], dAtA[iNdEx:postIndex]...)
			if m.Ftype == nil {
				m.Ftype = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Finfo", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Finfo = append(m.Finfo[:0], dAtA[iNdEx:postIndex]...)
			if m.Finfo == nil {
				m.Finfo = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fsum", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fsum = append(m.Fsum[:0], dAtA[iNdEx:postIndex]...)
			if m.Fsum == nil {
				m.Fsum = []byte{}
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fsize", wireType)
			}
			m.Fsize = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Fsize |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OffsetFrom", wireType)
			}
			m.OffsetFrom = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OffsetFrom |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OffsetTo", wireType)
			}
			m.OffsetTo = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.OffsetTo |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Misc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Misc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Misc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Mtype", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Mtype = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEntity
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEntity
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEntity(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEntity
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEntity(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEntity
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEntity
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEntity
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEntity
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEntity
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEntity        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEntity          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEntity = fmt.Errorf("proto: unexpected end of group")
)
